main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls'))
]

todo/urls.py
from django.urls import path
from .views import Index, AddTask, UpdateTask, UserOwnList, DeleteTask

app_name = "todo"

urlpatterns = [
    path('', Index.as_view(), name="home"),
    path('add', AddTask.as_view(), name="add"),
    path('update/<int:pk>/', UpdateTask.as_view(), name="update"),
    path('user/<int:pk>', UserOwnList.as_view(), name="solo" ),
    path('delete/<int:pk>', DeleteTask.as_view(), name="delete" ),

]

todo/models.py
from django.db import models

# Create your models here.
class TodoMod(models.Model):
  name = models.CharField(max_length=100)
  task = models.CharField(max_length=5000)
  completed = models.BooleanField(default=False)
  
  def __str__(self) -> str:
    return self.name

todo/views.py
from django.shortcuts import reverse
from django.views.generic import UpdateView, CreateView, ListView, DetailView, DeleteView
from .models import TodoMod
from django.urls import reverse_lazy

# Create your views here.
class Index(ListView):
  template_name = "base.html"
  queryset = TodoMod.objects.all()
  context_object_name = "todo_list"

  
class AddTask(CreateView):
  model = TodoMod
  fields = ['name','task']
  template_name = "base.html"
  success_url = reverse_lazy("todo:home")
  

class UpdateTask(UpdateView):
  model = TodoMod
  fields = ['completed']
  template_name = "base.html"
  success_url = reverse_lazy("todo:home")
  
class UserOwnList(DetailView):
  model = TodoMod
  template_name = "selftask.html"
  
  def get_success_url(self):
    pk_value = self.object.pk
    return reverse("todo:solo", kwargs={'pk': pk_value})

class DeleteTask(DeleteView):
  model = TodoMod
  template_name = "base.html"
  fields = "__all__"  
  success_url = reverse_lazy("todo:home")
 

  
      
  
  
 
  
 
  
    


   

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todo App - Django</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
        <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    </head>
    <body>
        <div style="margin-top: 50px;" class="ui container">
            <h1 class="ui center aligned header">Django ToDo App</h1>

            <form class="ui form" action='/add' method="post">
                {% csrf_token %}
                <div class="field">
                    <label>Todo Title</label>
                    <input type="text" name="name" placeholder="What's your name">
                    <input type="text" name="task" placeholder="Enter ToDo task...">
                    <br>
                </div>
                <button class="ui blue button" type="submit">Add</button>
            </form>

            <hr>

            {% for todo in todo_list %} 
            <div class="ui segment">
                <p class="ui big header">{{ todo.name }} | {{ todo.task }}</p>

                {% if todo.completed == False %}
                <span class="ui gray label">Not Complete</span>
                {% elif todo.completed == True %}
                <span class="ui green label">Complete</span>
                {% endif %}

                
                <form method="post" action="{% url 'todo:update' pk=todo.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="completed" value= True >
                    <button type="submit" class="ui blue button">Complete</button>
                </form> 

               <form method="post" action="{% url 'todo:delete' pk=todo.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="completed">
                    <button type="submit" class="ui red button">Delete</button>
                </form>  
                {% comment %} <a class="ui blue button" href="/update/{{ todo.id }}">Update</a> 
                <a class="ui red button" href="/delete/{{ todo.id }}">Delete</a>  {% endcomment %}

            </div>
            {% endfor %}
        </div>
    </body>
</html>

todo/templates/selftask.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Todo App - Django</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
        <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    </head>
    <body>
        <div style="margin-top: 50px;" class="ui container">
            <h1 class="ui center aligned header">{{object.name }} Tasks</h1>
            <hr>
            <div class="ui segment">
                <p class="ui big header">{{ object.name }} | {{ object.task }}</p>
            </div>
        </div>
    </body>
</html>